language: android

jdk: oraclejdk7

branches:
  only:
    - master
    - develop
    - /^bugfix.*$/
    - /^feature.*$/

android:
  components:
    - tools
    # The BuildTools version used by your project
    - build-tools-23.0.2
    # The SDK version used to compile your project
    - android-23
    # Additional components
    ## Google Play Services Library
    - extra-google-google_play_services
    ## Android Support Library (appcompat)
    - extra-android-support
    ## Android Support Repository
    - extra-android-m2repository
    ## Goodle Android Repository
    - extra-google-m2repository

# decrypt keystores
before_install:
- openssl aes-256-cbc -K $encrypted_3743ad7241be_key -iv $encrypted_3743ad7241be_iv -in ocyco.keystore.enc -out ocyco.keystore -d
- openssl aes-256-cbc -K $encrypted_3743ad7241be_key -iv $encrypted_3743ad7241be_iv -in ocyco-google-play.keystore.enc -out ocyco-google-play.keystore -d
- openssl aes-256-cbc -K $encrypted_3743ad7241be_key -iv $encrypted_3743ad7241be_iv -in play-keys.json.enc -out play-keys.json -d

script:
  - ./gradlew assembleBintray

after_script:
  - cat app/build/outputs/lint-results.html
  - ./gradlew signingReport

before_deploy:
  - TRAVIS_BRANCH_ESCAPED=$(echo "$TRAVIS_BRANCH" | sed -r 's/[/]+/-/g')
  - cp app/build/outputs/apk/app-bintray.apk app/build/outputs/apk/ocyco-app-$(date +%Y-%m-%d_%H-%M-%S)-$TRAVIS_BRANCH_ESCAPED-$TRAVIS_COMMIT.apk
  - ./upload.sh
  # Publish master and develop builds on Google Play
  - test "$TRAVIS_PULL_REQUEST" == "false" && test "$TRAVIS_BRANCH" == "develop" && ./gradlew publishApkPlayStore
#  - test "$TRAVIS_PULL_REQUEST" == "false" && test "$TRAVIS_BRANCH" == "master" && ./gradlew publishApkPlayStore

deploy:
  - provider: bintray
    skip_cleanup: true
    file: deploy-bintray.txt
    user: "rleh"
    key:
      secure: K5zoytQcAcc4fmf1hvZ+GOqxQEbBdteT+rOtXKAYyJk99W0YCeP9Huh9imF+h84LZQcN32O8Hhrl1pdjKcVMiCO8gf0zrA5TiG6JMUctv1qmlkz5uxO3Y/M8NSrhCstG0Oi8I8p9swvyZY3gRDdhjhwbvn4CaHa0B/Vu7DP85sQDvveMc7ynxKPZOljC23iBfRsvCA/nQm+2TfM/M4AnxxBM9s/ogQggbDVDxfrw0tAXHkFR1bgEHzSvdcNFOt7YwYOs4CAqGfWSEruzMbVYKclAzXTQ1RYEuK6Isu1H5PUZICkvP1c3uIarz6J2qsH/+AsiI+Fa8vOcizmT52MnK+nvIK9+JpSm6XoAcEnsb8kF4xna2wZp7jJQlS5Qb0/hcd3TJyiTqrlJBwvEfS6X8JoozJNErVLkYTLSbBcgcKopMamoA1l5Cng6tFLdlMaV+xMbZhjp7HtBMJLp6zjzHeWXE6e8LwP6grtuB8wIDKZxZjmMAOk0JIrvxOhHMuDqpbsnlLmT7gj1Ia1eFF5ApVn3ms2P8MXyh3bbXAqkaCL9VV1e22BesdC/2KYlOKmGTs8EDPwgjTy/mfF7Bzca2KpY6fP/McP5djgDm8LtBdZVRq9pHQWDZtgCed7ihF3mek/KRXG+ijhfQTtz30u3rnWWEI5gWOiRlyR/yBR1p7A=
    on:
      all_branches: true
